title: Temasek Launchpad
url: https://www.tp.edu.sg
favicon: /images/favicon.png
colors:
  primary-color: "#1b0f2a"
  secondary-color: "#8328ff"
  media-colors:
    - title: media-color-one
      color: "#f57f20"
    - title: media-color-two
      color: "#eb008b"
    - title: media-color-three
      color: "#0086ff"
    - title: media-color-four
      color: "#fffaf5"
    - title: media-color-five
      color: "#e6e7e8"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d1ww3f03vnzgjb.amplifyapp.com
prod: https://master.d3qhfmy477grha.amplifyapp.com
facebook-pixel: ""
resources_name: test
shareicon: /images/TP_Logo.png
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
